export const CREATE_NOTE = 'CREATE_NOTE';
export const DELETE_NOTES = 'DELETE_NOTES';
export const MARKED_ALL_NOTES_AS_READ = 'MARKED_ALL_NOTES_AS_READ';
export const GET_ALL_NOTES = 'GET_ALL_NOTES';

export const TOGGLE_UNREAD_NOTES_POPOVER = 'TOGGLE_UNREAD_NOTES_POPOVER';